version: 2.1
orbs:
  cypress: cypress-io/cypress@14.3.2
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
          - cypress/install
        store_artifats: true
        parallel: true
        parallelism: 3
        group: 2 machines