jobs:
  install-deps:
    docker:
      - image: cimg/node:18.20-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cypress-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-cypress-
      - run:
          name: Install dependencies
          command: |
            npm ci
            npx cypress install   # upewnia się, że binarka się pobierze
      - save_cache:
          key: v1-cypress-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/Cypress
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - package-lock.json
