version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: "cypress-run-1"
          requires:
            - cypress/install
      - cypress/run:
          name: "cypress-run-2" 
          requires:
            - cypress/install
      - cypress/run:
          name: "cypress-run-3"
          requires:
            - cypress/install